/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco;

import static banco.Padre.depo;
import static banco.Padre.dinero;
import static banco.Padre.retiro;
import static banco.Padre.txt_buscar;
import funciones.Consulta;
import funciones.Deposito;
import funciones.Retiro;
import java.awt.Color;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.UIManager;
import java.sql.*;



/**
 *yomarli
 */
public class Usuario_BD extends javax.swing.JFrame {

    int xmouse, ymouse;
    UIManager UI;

    /**
     * Creates new form Usuario_BD
     */
    public Usuario_BD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backhround = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserLa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        Mover = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        UserLa1 = new javax.swing.JLabel();
        DMonto = new javax.swing.JLabel();
        UserLa3 = new javax.swing.JLabel();
        UserLa4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Consulta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Registro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Depositar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Retirar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Modificar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        Ddepo = new javax.swing.JLabel();
        Dreti = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Modificar1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Backhround.setBackground(new java.awt.Color(255, 255, 255));
        Backhround.setMinimumSize(new java.awt.Dimension(990, 678));
        Backhround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 190, 131)));

        mostrar.setColumns(20);
        mostrar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        mostrar.setRows(5);
        mostrar.setBorder(null);
        jScrollPane2.setViewportView(mostrar);

        Backhround.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 390, 220));

        label2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        label2.setText("Las Abejitas");
        Backhround.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/favicon.png"))); // NOI18N
        jLabel2.setText("Bienvenido");
        Backhround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 40));

        UserLa.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        UserLa.setText("Usuario:");
        Backhround.add(UserLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/beeci.jpg"))); // NOI18N
        Backhround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 390, 680));

        T1.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        T1.setForeground(new java.awt.Color(204, 204, 204));
        T1.setBorder(null);
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T1MousePressed(evt);
            }
        });
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        Backhround.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 30));

        Mover.setBackground(new java.awt.Color(255, 255, 255));
        Mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverMouseDragged(evt);
            }
        });
        Mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverMousePressed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(245, 190, 131));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitMouseDragged(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MoverLayout = new javax.swing.GroupLayout(Mover);
        Mover.setLayout(MoverLayout);
        MoverLayout.setHorizontalGroup(
            MoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(967, Short.MAX_VALUE))
        );
        MoverLayout.setVerticalGroup(
            MoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoverLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Backhround.add(Mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1020, 40));

        UserLa1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        UserLa1.setText("Último depósito:");
        Backhround.add(UserLa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        DMonto.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        DMonto.setForeground(new java.awt.Color(204, 204, 204));
        DMonto.setText(".....");
        Backhround.add(DMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 180, 30));

        UserLa3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        UserLa3.setText("Último Retiro:");
        Backhround.add(UserLa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        UserLa4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        UserLa4.setText("Monto Actual:");
        Backhround.add(UserLa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jPanel1.setBackground(new java.awt.Color(245, 190, 131));

        Consulta.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Consulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Consulta.setText("Consultar");
        Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConsultaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Backhround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 110, 50));

        jPanel2.setBackground(new java.awt.Color(245, 190, 131));

        Registro.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registro.setText("Registrar");
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Backhround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 110, 50));

        jPanel3.setBackground(new java.awt.Color(245, 190, 131));

        Depositar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Depositar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Depositar.setText("Depositar");
        Depositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Depositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepositarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepositarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Backhround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(245, 190, 131));

        Retirar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Retirar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Retirar.setText("Retirar");
        Retirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetirarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RetirarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Backhround.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jPanel5.setBackground(new java.awt.Color(245, 190, 131));

        Modificar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modificar.setText("Modificar");
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Backhround.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jPanel6.setBackground(new java.awt.Color(245, 190, 131));

        Eliminar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eliminar.setText("Eliminar");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Eliminar.getAccessibleContext().setAccessibleParent(jPanel5);

        Backhround.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        Ddepo.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Ddepo.setForeground(new java.awt.Color(204, 204, 204));
        Ddepo.setText(".....");
        Backhround.add(Ddepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 250, 30));

        Dreti.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Dreti.setForeground(new java.awt.Color(204, 204, 204));
        Dreti.setText(".....");
        Backhround.add(Dreti, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Backhround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 212, 250, 10));

        Modificar1.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Modificar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modificar1.setText("Modificar");
        Modificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modificar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Modificar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Modificar1MouseExited(evt);
            }
        });
        Backhround.add(Modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Backhround.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Backhround, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backhround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed

    }//GEN-LAST:event_exitMousePressed

    private void exitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseDragged

    }//GEN-LAST:event_exitMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(Color.white);
        exit.setForeground(new Color(245, 190, 131));
    }//GEN-LAST:event_exitMouseExited

    private void RegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMouseEntered
        Registro.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_RegistroMouseEntered

    private void RegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMouseExited
        Registro.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_RegistroMouseExited

    private void ConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseEntered
        Consulta.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_ConsultaMouseEntered

    private void ConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseExited
        Consulta.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_ConsultaMouseExited

    private void DepositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositarMouseEntered
        Depositar.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_DepositarMouseEntered

    private void DepositarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositarMouseExited
        Depositar.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_DepositarMouseExited

    private void RetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseEntered
        Retirar.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_RetirarMouseEntered

    private void RetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseExited
        Retirar.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_RetirarMouseExited

    private void ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseEntered
        Modificar.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_ModificarMouseEntered

    private void ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseExited
        Modificar.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_ModificarMouseExited

    private void EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseEntered
        Eliminar.setBackground(new Color(252, 220, 186));
    }//GEN-LAST:event_EliminarMouseEntered

    private void EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseExited
        Eliminar.setBackground(new Color(245, 190, 131));
    }//GEN-LAST:event_EliminarMouseExited

    private void RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMouseClicked
        UI = null;
        UI.put("control", new Color(245, 190, 131));
        UI.put("OptionPane.background", new Color(245, 190, 131));
        try { // int x = 0
            //Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_bank", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into sistema values(?,?,?,?,?)");
            if (!T1.getText().isEmpty()) {
                pst.setString(1, "0");
                pst.setString(2, T1.getText().trim());
                pst.setString(3, DMonto.getText().trim());
                pst.setString(4, Ddepo.getText().trim());
                pst.setString(5, Dreti.getText().trim());
                pst.executeUpdate();
                T1.setText("");
                Ddepo.setText("");
                Dreti.setText("");
                mostrar.setText("");
                DMonto.setText("");
                dinero = 0;
                JOptionPane.showMessageDialog(null, "Registro Exitoso", "Registro", JOptionPane.PLAIN_MESSAGE, icono("/iconos/regis.png", 40, 40));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.PLAIN_MESSAGE, icono("/iconos/error.png", 40, 40));
        }
    }//GEN-LAST:event_RegistroMouseClicked

    private void ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseClicked
        UI = null;
        UI.put("control", new Color(245, 190, 131));
        UI.put("OptionPane.background", new Color(245, 190, 131));
        txt_buscar = valueOf(JOptionPane.showInputDialog(null, new JLabel("Código ID: ", icono("/iconos/consu.png", 40, 40), JLabel.LEADING), "Búsqueda", JOptionPane.PLAIN_MESSAGE));
        try {  
            //Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_bank", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from sistema where ID = ?");
            pst.setString(1, txt_buscar.trim());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                dinero = Float.parseFloat(rs.getString("TMonto"));
                T1.setText(rs.getString("Nombre"));
                T1.setForeground(Color.BLACK);
                Ddepo.setText(rs.getString("UDeposito"));
                Ddepo.setForeground(Color.BLACK);
                Dreti.setText(rs.getString("Uretiro"));
                Dreti.setForeground(Color.BLACK);
                DMonto.setText(rs.getString("TMonto"));
                DMonto.setForeground(Color.BLACK);
                mostrar.setText("Usuario: " + rs.getString("Nombre") + "\n"
                        + "Último Monto Total: " + rs.getString("TMonto") + "\n"
                        + "Último Depósito: " + rs.getString("UDeposito") + "\n"
                        + "Último Retiro: " + rs.getString("URetiro"));
            } else {
                T1.setText("");
                Ddepo.setText("");
                Dreti.setText("");
                mostrar.setText("");
                DMonto.setText("");
                mostrar.setText("No se encuentra en la base de datos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.PLAIN_MESSAGE, icono("/iconos/error.png", 40, 40));

        }
    }//GEN-LAST:event_ConsultaMouseClicked

    private void DepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositarMouseClicked
        //Class.forName("com.mysql.jdbc.Driver");
        Deposito men2 = new Deposito();
        men2.Operaciones();
        Ddepo.setText("");
        Ddepo.setText(valueOf(depo));
        Consulta men = new Consulta();
        men.Operaciones();
        Ddepo.setForeground(Color.BLACK);
        DMonto.setText(valueOf(dinero));
        DMonto.setForeground(Color.BLACK);
    }//GEN-LAST:event_DepositarMouseClicked

    private void RetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseClicked
        //Class.forName("com.mysql.jdbc.Driver");
        Retiro men3 = new Retiro();
        men3.Operaciones();
        Dreti.setText("");
        Dreti.setText(valueOf(retiro));
        Consulta men = new Consulta();
        men.Operaciones();
        Dreti.setForeground(Color.BLACK);
        DMonto.setText(valueOf(dinero));
        DMonto.setForeground(Color.BLACK);
    }//GEN-LAST:event_RetirarMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        UI = null;
        UI.put("control", new Color(245, 190, 131));
        UI.put("OptionPane.background", new Color(245, 190, 131));
        txt_buscar = valueOf(JOptionPane.showInputDialog(null, new JLabel("Código: ", icono("/iconos/consu.png", 40, 40), JLabel.LEADING), "Búsqueda", JOptionPane.PLAIN_MESSAGE));
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            String ID = txt_buscar.trim();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_bank", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from sistema where ID = ?");
            pst.setString(1, txt_buscar.trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                pst = cn.prepareStatement("update sistema set Nombre=?,TMonto=?,UDeposito=?,URetiro=? where ID=" + ID);

                pst.setString(1, T1.getText().trim());
                pst.setString(2, DMonto.getText().trim());
                pst.setString(3, Ddepo.getText().trim());
                pst.setString(4, Dreti.getText().trim());
                pst.executeUpdate();
                dinero = 0;
                JOptionPane.showMessageDialog(null, "Modificación Exitoso", "Modificar", JOptionPane.PLAIN_MESSAGE, icono("/iconos/modif.png", 40, 40));
                T1.setText("");
                Ddepo.setText("");
                Dreti.setText("");
                mostrar.setText("");
                DMonto.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no registrado", "No registra", JOptionPane.PLAIN_MESSAGE, icono("/iconos/no_user.png", 40, 40));

            }
            txt_buscar = "";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.PLAIN_MESSAGE, icono("/iconos/error.png", 40, 40));
        }
    }//GEN-LAST:event_ModificarMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        UI = null;
        UI.put("control", new Color(245, 190, 131));
        UI.put("OptionPane.background", new Color(245, 190, 131));
        txt_buscar = valueOf(JOptionPane.showInputDialog(null, new JLabel("Código: ", icono("/iconos/consu.png", 40, 40), JLabel.LEADING), "Búsqueda", JOptionPane.PLAIN_MESSAGE));
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            String ID = txt_buscar.trim();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_bank", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from sistema where ID = ?");
            pst.setString(1, txt_buscar.trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                pst = cn.prepareStatement("delete from sistema where ID = ?");
                pst.setString(1, txt_buscar.trim());
                T1.setText("");
                Ddepo.setText("");
                Dreti.setText("");
                mostrar.setText("");
                DMonto.setText("");
                pst.executeUpdate();
                dinero = 0;
                JOptionPane.showMessageDialog(null, "Usuario eliminado", "Eliminar", JOptionPane.PLAIN_MESSAGE, icono("/iconos/dele.png", 40, 40));
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no registrado", "No registra", JOptionPane.PLAIN_MESSAGE, icono("/iconos/no_user.png", 40, 40));
            }
txt_buscar = "";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.PLAIN_MESSAGE, icono("/iconos/error.png", 40, 40));
        }
    }//GEN-LAST:event_EliminarMouseClicked

    private void T1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MousePressed
        T1.setText("");
        T1.setForeground(Color.BLACK);
    }//GEN-LAST:event_T1MousePressed

    private void MoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_MoverMousePressed

    private void MoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_MoverMouseDragged

    private void Modificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modificar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Modificar1MouseClicked

    private void Modificar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modificar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Modificar1MouseEntered

    private void Modificar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modificar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Modificar1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UI = null;
        UI.put("control", new Color(245, 190, 131));
        UI.put("OptionPane.background", new Color(245, 190, 131));
        
        Document documento = new Document();
        
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_Clientes.pdf"));
            documento.open();
            
            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("Código");
            tabla.addCell("Nombre");
            tabla.addCell("Monto Total");
            tabla.addCell("Último Depósito");
            tabla.addCell("Último Retiro");
            
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_bank", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from sistema");
                
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                    } while(rs.next());
                    documento.add(tabla);
                }
            }catch(DocumentException | SQLException e){    
            }
            
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte creado.", "PDF", JOptionPane.PLAIN_MESSAGE, icono("/iconos/abejita.png", 40, 40));
        
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            
        } 
    }//GEN-LAST:event_jButton1ActionPerformed
    public Icon icono(String path, int ancho, int altura) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().getScaledInstance(ancho, altura, java.awt.Image.SCALE_SMOOTH));
        return img;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_BD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backhround;
    private javax.swing.JLabel Consulta;
    private javax.swing.JLabel DMonto;
    private javax.swing.JLabel Ddepo;
    private javax.swing.JLabel Depositar;
    private javax.swing.JLabel Dreti;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel Modificar1;
    private javax.swing.JPanel Mover;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel Retirar;
    private javax.swing.JTextField T1;
    private javax.swing.JLabel UserLa;
    private javax.swing.JLabel UserLa1;
    private javax.swing.JLabel UserLa3;
    private javax.swing.JLabel UserLa4;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label2;
    private javax.swing.JTextArea mostrar;
    // End of variables declaration//GEN-END:variables

    private static class PdfPtable {

        public PdfPtable() {
        }
    }
}
